In [9]:
import numpy

class neuralNetWork :
    
    def __init__(self, inputnodes, hiddennodes, outputnodes, learningrate):
        self.inodes = inputnodes
        self.hnodes = hiddennodes
        self.onodes = outputnodes
        self.lr = learningrate
        
        # self.wih = numpy.random.rand(self.hnodes, self.inodes)-0.5
        # self.who = numpy.random.rand(self.onodes, self.hnodes)-0.5
        
        
        self.wih = numpy.random.normal(0.0, pow(self.hnodes, -0.5), (self.hnodes, self.inodes))
        self.wih = numpy.random.normal(0.0, pow(self.hnodes, -0.5), (self.hnodes, self.inodes))
        print self.wih
        pass
    
    def train():
        
        pass
    
    def query():
        pass
    

In [10]:
input_nodes = 3
hiden_nodes = 3
output_nodes = 3
learn_rate = 0.5

n = neuralNetWork(input_nodes, hiden_nodes, output_nodes, learn_rate)


[[ 0.93731058  0.47842226  0.51156205]
 [-0.26980742 -0.50447129  0.57107416]
 [ 0.01896767 -0.60594816 -0.28775455]]
